apiVersion: v1
kind: pod
metadata:
  name: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    spec:
      containers:
      - name: transmission
        image: lscr.io/linuxserver/transmission:latest
