apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: transmission
spec:
  selector:
    matchLabels:
      new-label: transmission
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        new-label: transmission
    spec:
      containers:
      - name: transmission
        image: jomedei/transmissionv02:latest
        ports:
        - containerPort: 9091
        command: ["/bin/sh","-c"]
        args: [ "/etc/init.d/transmission-daemon start; sleep infinity" ]
---
apiVersion: v1
kind: Service
metadata:
  name: service9091
spec:
  type: LoadBalancer
  selector:
    new-label: transmission
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9091
