apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: transmission
spec:
  selector:
    matchLabels:
      new-label: transmission
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        new-label: transmission
    spec:
      containers:
      - name: transmission
        image: jomedei/transmissionv01:latest
        command: [ "sleep" ]
        args: [ "infinity" ]
